# Generated by Django 4.0.4 on 2022-05-11 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_stack_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='stack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.stack'),
            preserve_default=False,
        ),
    ]
