# Generated by Django 4.0.4 on 2022-05-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='stack',
        ),
        migrations.AddField(
            model_name='stack',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.question'),
            preserve_default=False,
        ),
    ]
