# Generated by Django 4.0.4 on 2022-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_stack_question_question_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='the_question',
            field=models.CharField(help_text='Question', max_length=100),
        ),
    ]
